kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-retry-api-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: KAFKA_RETRY_TOPICNAME
      value: eessipensjon.privat-retry-q2
    - name: S3_URL
      value: http://objectstore.rook-ceph.svc.nais.local
    - name: S3_REGION
      value: us-east-1
    - name: ENV
      value: q2

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-retry-api-q2.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{appsecrets}}
        mountPath: /var/run/secrets/nais.io/appcredentials
