kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-retry-api
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: KAFKA_RETRY_TOPICNAME
      value: eessipensjon.privat-retry
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: S3_URL
      value: http://objectstore.rook-ceph.svc.nais.local
    - name: EESSI_PENSJON_RETRY_S3_CREDS_USERNAME
      value: 4BCDP6BBQVV56JZDIGL3
    - name: ENV
      value: p

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-retry-api.nais.adeo.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
#  vault:
#    enabled: true
#    paths:
#      - kvPath: {{appsecrets}}
#        mountPath: /var/run/secrets/nais.io/appcredentials
