name: Deploy PROD
on:
  repository_dispatch:
    types: [deploy-prod]
jobs:
  tag_deploy_q1:
    name: 'Deploy til PROD'
    runs-on: ubuntu-latest
    steps:
      # GET version
      - name: 'Get the version'
        uses: actions/checkout@v2

      # Show IMAGE from Q2 deploy
      - name: 'Vise image'
        run: |
          echo "image-tag: ${{ github.event.client_payload.image }}"
